export const FETCH_VIDEO = 'FETCH_VIDEO';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_LIST = 'UPDATE_LIST';
export const FETCH_MORE_VIDEO = 'FETCH_MORE_VIDEO';
export const ADD_VIDEO = 'ADD_VIDEO';
